name: Execute tests on new Hosted
on:
  workflow_dispatch:

env:
  K8S_VERSION: "v1.30.2"
  KUBE_BURNER_VERSION: "1.9.8"

jobs:
  python-action-test:
    runs-on: self-hosted
    steps:
    - run: uname -i
    - uses: actions/checkout@v4
