name: Execute tests on new Hosted
on:
  workflow_dispatch:

env:
  K8S_VERSION: "v1.30.2"
  KUBE_BURNER_VERSION: "1.9.8"
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  python-action-test:
    runs-on: self-hosted
    steps:
    - run: uname -i
    
    - name: Checkout
      uses: actions/checkout@v3
